// Code generated by goctl. DO NOT EDIT.
package types

// The basic response with data | 基础带数据信息
// swagger:model BaseDataInfo
type BaseDataInfo struct {
	// Error code | 错误代码
	Code int `json:"code"`
	// Message | 提示信息
	Msg string `json:"msg"`
	// Data | 数据
	Data string `json:"data,omitempty"`
}

// The basic response with data | 基础带数据信息
// swagger:model BaseListInfo
type BaseListInfo struct {
	// The total number of data | 数据总数
	Total uint64 `json:"total"`
}

// The basic response without data | 基础不带数据信息
// swagger:model BaseMsgResp
type BaseMsgResp struct {
	// Error code | 错误代码
	Code int `json:"code"`
	// Message | 提示信息
	Msg string `json:"msg"`
}

// The page request parameters | 列表请求参数
// swagger:model PageInfo
type PageInfo struct {
	// Page number | 第几页
	// min : 0
	Page uint64 `json:"page,optional" form:"page,default=1" validate:"number,gt=0"`
	// Page size | 单页数据行数
	// max : 100000
	PageSize uint64 `json:"pageSize,optional" form:"pageSize,default=10" validate:"number,lt=100000"`
}

// Basic ID request | 基础ID参数请求
// swagger:model IDReq
type IDReq struct {
	// ID
	// Required: true
	Id uint64 `json:"id" validate:"number"`
}

// Basic IDs request | 基础ID数组参数请求
// swagger:model IDsReq
type IDsReq struct {
	// IDs
	// Required: true
	Ids []uint64 `json:"ids"`
}

// Basic ID request | 基础ID地址参数请求
// swagger:model IDPathReq
type IDPathReq struct {
	// ID
	// Required: true
	Id uint64 `path:"id"`
}

// Basic ID request (int32) | 基础ID参数请求 (int32)
// swagger:model IDInt32Req
type IDInt32Req struct {
	// ID
	// Required: true
	Id int32 `json:"id" validate:"number"`
}

// Basic IDs request (int32) | 基础ID数组参数请求 (int32)
// swagger:model IDsInt32Req
type IDsInt32Req struct {
	// IDs
	// Required: true
	Ids []int32 `json:"ids"`
}

// Basic ID request (int32) | 基础ID地址参数请求 (int32)
// swagger:model IDInt32PathReq
type IDInt32PathReq struct {
	// ID
	// Required: true
	Id int32 `path:"id"`
}

// Basic ID request (uint32) | 基础ID参数请求 (uint32)
// swagger:model IDUint32Req
type IDUint32Req struct {
	// ID
	// Required: true
	Id uint32 `json:"id" validate:"number"`
}

// Basic IDs request (uint32) | 基础ID数组参数请求 (uint32)
// swagger:model IDsUint32Req
type IDsUint32Req struct {
	// IDs
	// Required: true
	Ids []uint32 `json:"ids"`
}

// Basic ID request (uint32) | 基础ID地址参数请求 (uint32)
// swagger:model IDUint32PathReq
type IDUint32PathReq struct {
	// ID
	// Required: true
	Id uint32 `path:"id"`
}

// Basic ID request (int64) | 基础ID参数请求 (int64)
// swagger:model IDInt64Req
type IDInt64Req struct {
	// ID
	// Required: true
	Id int64 `json:"id" validate:"number"`
}

// Basic IDs request (int64) | 基础ID数组参数请求 (int64)
// swagger:model IDsInt64Req
type IDsInt64Req struct {
	// IDs
	// Required: true
	Ids []int64 `json:"ids"`
}

// Basic ID request (int64) | 基础ID地址参数请求 (int64)
// swagger:model IDInt64PathReq
type IDInt64PathReq struct {
	// ID
	// Required: true
	Id int64 `path:"id"`
}

// Basic ID request (string) | 基础ID参数请求 (string)
// swagger:model IDStringReq
type IDStringReq struct {
	// ID
	// Required: true
	Id string `json:"id"`
}

// Basic IDs request (string) | 基础ID数组参数请求 (string)
// swagger:model IDsStringReq
type IDsStringReq struct {
	// IDs
	// Required: true
	Ids []string `json:"ids"`
}

// Basic ID request (string) | 基础ID地址参数请求 (string)
// swagger:model IDStringPathReq
type IDStringPathReq struct {
	// ID
	// Required: true
	Id string `path:"id"`
}

// Basic UUID request in path | 基础UUID地址参数请求
// swagger:model UUIDPathReq
type UUIDPathReq struct {
	// ID
	// Required: true
	Id string `path:"id"`
}

// Basic UUID request | 基础UUID参数请求
// swagger:model UUIDReq
type UUIDReq struct {
	// ID
	// required : true
	// max length : 36
	// min length : 36
	Id string `json:"id" validate:"required,len=36"`
}

// Basic UUID array request | 基础UUID数组参数请求
// swagger:model UUIDsReq
type UUIDsReq struct {
	// Ids
	// Required: true
	Ids []string `json:"ids"`
}

// The base ID response data | 基础ID信息
// swagger:model BaseIDInfo
type BaseIDInfo struct {
	// ID
	Id *uint64 `json:"id,optional"`
	// Create date | 创建日期
	CreatedAt *int64 `json:"createdAt,optional"`
	// Update date | 更新日期
	UpdatedAt *int64 `json:"updatedAt,optional"`
}

// The base ID response data (int64) | 基础ID信息 (int64)
// swagger:model BaseIDInt64Info
type BaseIDInt64Info struct {
	// ID
	Id *int64 `json:"id,optional"`
	// Create date | 创建日期
	CreatedAt *int64 `json:"createdAt,optional"`
	// Update date | 更新日期
	UpdatedAt *int64 `json:"updatedAt,optional"`
}

// The base ID response data (int32) | 基础ID信息 (int32)
// swagger:model BaseIDInt32Info
type BaseIDInt32Info struct {
	// ID
	Id *int32 `json:"id,optional"`
	// Create date | 创建日期
	CreatedAt *int64 `json:"createdAt,optional"`
	// Update date | 更新日期
	UpdatedAt *int64 `json:"updatedAt,optional"`
}

// The base ID response data (uint32) | 基础ID信息 (uint32)
// swagger:model BaseIDUint32Info
type BaseIDUint32Info struct {
	// ID
	Id *uint32 `json:"id,optional"`
	// Create date | 创建日期
	CreatedAt *int64 `json:"createdAt,optional"`
	// Update date | 更新日期
	UpdatedAt *int64 `json:"updatedAt,optional"`
}

// The base UUID response data | 基础UUID信息
// swagger:model BaseUUIDInfo
type BaseUUIDInfo struct {
	// ID
	Id *string `json:"id,optional"`
	// Create date | 创建日期
	CreatedAt *int64 `json:"createdAt,optional"`
	// Update date | 更新日期
	UpdatedAt *int64 `json:"updatedAt,optional"`
}

// The base ID response data (string) | 基础ID信息 (string)
// swagger:model BaseIDStringInfo
type BaseIDStringInfo struct {
	// ID
	Id *string `json:"id,optional"`
	// Create date | 创建日期
	CreatedAt *int64 `json:"createdAt,optional"`
	// Update date | 更新日期
	UpdatedAt *int64 `json:"updatedAt,optional"`
}

// 发现池信息
// swagger:model DiscoveryPoolInfo
type DiscoveryPoolInfo struct {
	BaseIDInfo
	// 基础信息
	Name          string `json:"name"`          // 发现池名称
	Description   string `json:"description"`   // 发现池描述
	DiscoveryType string `json:"discoveryType"` // 发现类型: file, api, sdk, builtin
	PoolStatus    string `json:"poolStatus"`    // 池状态: active, inactive, error, maintain
	// 配置信息
	DiscoveryConfig string `json:"discoveryConfig"` // 发现配置JSON
	Schedule        string `json:"schedule"`        // 调度表达式
	BatchSize       int    `json:"batchSize"`       // 批处理大小
	ConcurrentLimit int    `json:"concurrentLimit"` // 并发限制
	// 重试配置
	MaxRetry      int `json:"maxRetry"`      // 最大重试次数
	RetryInterval int `json:"retryInterval"` // 重试间隔
	// 字段映射
	FieldMapping string `json:"fieldMapping"` // 字段映射配置JSON
	// 运行统计
	TotalRuns   int64 `json:"totalRuns"`   // 总执行次数
	SuccessRuns int64 `json:"successRuns"` // 成功执行次数
	FailedRuns  int64 `json:"failedRuns"`  // 失败执行次数
	// 最后执行信息
	LastRunAt     *int64  `json:"lastRunAt,optional"`     // 最后执行时间
	LastSuccessAt *int64  `json:"lastSuccessAt,optional"` // 最后成功时间
	LastError     *string `json:"lastError,optional"`     // 最后错误信息
	// 审核流程
	ApprovalStatus  string  `json:"approvalStatus"`           // 审核状态: pending, approved, rejected
	ApprovedBy      *uint64 `json:"approvedBy,optional"`      // 审核人ID
	ApprovedAt      *int64  `json:"approvedAt,optional"`      // 审核时间
	RejectionReason *string `json:"rejectionReason,optional"` // 拒绝原因
	// 扩展元数据
	Metadata string `json:"metadata"` // 扩展元数据JSON
}

// 发现池列表响应
// swagger:model DiscoveryPoolListResp
type DiscoveryPoolListResp struct {
	BaseDataInfo
	Data DiscoveryPoolListData `json:"data"`
}

type DiscoveryPoolListData struct {
	BaseListInfo
	Data []DiscoveryPoolInfo `json:"data"`
}

// 发现池信息响应
// swagger:model DiscoveryPoolInfoResp
type DiscoveryPoolInfoResp struct {
	BaseDataInfo
	Data DiscoveryPoolInfo `json:"data"`
}

// 创建发现池请求
// swagger:model CreateDiscoveryPoolReq
type CreateDiscoveryPoolReq struct {
	Name            string  `json:"name"`                     // 发现池名称
	Description     *string `json:"description,optional"`     // 发现池描述
	DiscoveryType   string  `json:"discoveryType"`            // 发现类型
	DiscoveryConfig *string `json:"discoveryConfig,optional"` // 发现配置JSON
	Schedule        *string `json:"schedule,optional"`        // 调度表达式
	BatchSize       *int    `json:"batchSize,optional"`       // 批处理大小
	ConcurrentLimit *int    `json:"concurrentLimit,optional"` // 并发限制
	MaxRetry        *int    `json:"maxRetry,optional"`        // 最大重试次数
	RetryInterval   *int    `json:"retryInterval,optional"`   // 重试间隔
	FieldMapping    *string `json:"fieldMapping,optional"`    // 字段映射配置JSON
	Metadata        *string `json:"metadata,optional"`        // 扩展元数据JSON
}

// 更新发现池请求
// swagger:model UpdateDiscoveryPoolReq
type UpdateDiscoveryPoolReq struct {
	Id              uint64  `json:"id"`                       // 发现池ID
	Name            *string `json:"name,optional"`            // 发现池名称
	Description     *string `json:"description,optional"`     // 发现池描述
	DiscoveryType   *string `json:"discoveryType,optional"`   // 发现类型
	DiscoveryConfig *string `json:"discoveryConfig,optional"` // 发现配置JSON
	Schedule        *string `json:"schedule,optional"`        // 调度表达式
	BatchSize       *int    `json:"batchSize,optional"`       // 批处理大小
	ConcurrentLimit *int    `json:"concurrentLimit,optional"` // 并发限制
	MaxRetry        *int    `json:"maxRetry,optional"`        // 最大重试次数
	RetryInterval   *int    `json:"retryInterval,optional"`   // 重试间隔
	FieldMapping    *string `json:"fieldMapping,optional"`    // 字段映射配置JSON
	Metadata        *string `json:"metadata,optional"`        // 扩展元数据JSON
}

// 发现池列表查询请求
// swagger:model GetDiscoveryPoolListReq
type GetDiscoveryPoolListReq struct {
	PageInfo
	Name           *string `json:"name,optional"`           // 名称过滤
	DiscoveryType  *string `json:"discoveryType,optional"`  // 发现类型过滤
	PoolStatus     *string `json:"poolStatus,optional"`     // 状态过滤
	ApprovalStatus *string `json:"approvalStatus,optional"` // 审核状态过滤
}

// 审核发现池请求
// swagger:model ApproveDiscoveryPoolReq
type ApproveDiscoveryPoolReq struct {
	Id     uint64  `json:"id"`              // 发现池ID
	Action string  `json:"action"`          // 审核动作: approve, reject
	Reason *string `json:"reason,optional"` // 拒绝原因(拒绝时必填)
}

// swagger:model DiscoveryTemplateInfo
type DiscoveryTemplateInfo struct {
	Id                    uint64  `json:"id"`
	CreatedAt             int64   `json:"createdAt"`
	UpdatedAt             int64   `json:"updatedAt"`
	Status                uint8   `json:"status"`
	TenantId              uint64  `json:"tenantId"`
	TemplateName          string  `json:"templateName"`
	TemplateCode          string  `json:"templateCode"`
	Description           *string `json:"description,optional"`
	Version               string  `json:"version"`
	TemplateType          string  `json:"templateType"`
	DiscoveryConfig       *string `json:"discoveryConfig,optional"`
	FieldMappingTemplates *string `json:"fieldMappingTemplates,optional"`
	ValidationRules       *string `json:"validationRules,optional"`
	IsPublic              bool    `json:"isPublic"`
	IsSystem              bool    `json:"isSystem"`
	UsageCount            int64   `json:"usageCount"`
	Tags                  *string `json:"tags,optional"`
	Metadata              *string `json:"metadata,optional"`
}

// swagger:model CreateDiscoveryTemplateReq
type CreateDiscoveryTemplateReq struct {
	TemplateName          string  `json:"templateName"`
	TemplateCode          string  `json:"templateCode"`
	Description           *string `json:"description,optional"`
	Version               *string `json:"version,optional"`
	TemplateType          *string `json:"templateType,optional"`
	DiscoveryConfig       *string `json:"discoveryConfig,optional"`
	FieldMappingTemplates *string `json:"fieldMappingTemplates,optional"`
	ValidationRules       *string `json:"validationRules,optional"`
	IsPublic              *bool   `json:"isPublic,optional"`
	Tags                  *string `json:"tags,optional"`
	Metadata              *string `json:"metadata,optional"`
}

// swagger:model UpdateDiscoveryTemplateReq
type UpdateDiscoveryTemplateReq struct {
	Id                    uint64  `json:"id"`
	TemplateName          *string `json:"templateName,optional"`
	Description           *string `json:"description,optional"`
	Version               *string `json:"version,optional"`
	TemplateType          *string `json:"templateType,optional"`
	DiscoveryConfig       *string `json:"discoveryConfig,optional"`
	FieldMappingTemplates *string `json:"fieldMappingTemplates,optional"`
	ValidationRules       *string `json:"validationRules,optional"`
	IsPublic              *bool   `json:"isPublic,optional"`
	Tags                  *string `json:"tags,optional"`
	Metadata              *string `json:"metadata,optional"`
}

// swagger:model DiscoveryTemplateListReq
type DiscoveryTemplateListReq struct {
	Page         uint64  `json:"page"`
	PageSize     uint64  `json:"pageSize"`
	TemplateType *string `json:"templateType,optional"`
	IsPublic     *bool   `json:"isPublic,optional"`
	IsSystem     *bool   `json:"isSystem,optional"`
	Keyword      *string `json:"keyword,optional"`
}

// swagger:model DiscoveryTemplateListResp
type DiscoveryTemplateListResp struct {
	Total uint64                  `json:"total"`
	Data  []DiscoveryTemplateInfo `json:"data"`
}

type ParameterDefinition struct {
	Name         string      `json:"name"`
	Label        string      `json:"label"`
	Type         string      `json:"type"`
	Required     bool        `json:"required"`
	DefaultValue interface{} `json:"defaultValue,omitempty"`
	Placeholder  string      `json:"placeholder,omitempty"`
	Options      []string    `json:"options,omitempty"`
	Description  string      `json:"description,omitempty"`
}

type FieldDefinition struct {
	Name        string `json:"name"`
	Label       string `json:"label"`
	DataType    string `json:"dataType"`
	Required    bool   `json:"required"`
	Description string `json:"description,omitempty"`
	Example     string `json:"example,omitempty"`
}

type ProviderMetadata struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Category    string `json:"category"`
	Description string `json:"description,omitempty"`
	Version     string `json:"version,omitempty"`
	Icon        string `json:"icon,omitempty"`
}

// swagger:model ProviderSchemaInfo
type ProviderSchemaInfo struct {
	Id              string                `json:"id"`
	ProviderId      string                `json:"providerId"`
	ProviderName    string                `json:"providerName"`
	Category        string                `json:"category"`
	Description     string                `json:"description,omitempty"`
	Version         string                `json:"version,omitempty"`
	IconUrl         string                `json:"iconUrl,omitempty"`
	ParameterSchema []ParameterDefinition `json:"parameterSchema"`
	FieldSchema     []FieldDefinition     `json:"fieldSchema"`
	IsActive        bool                  `json:"isActive"`
	IsBuiltin       bool                  `json:"isBuiltin"`
	ExecutionMode   string                `json:"executionMode"`
}

// swagger:model ListProvidersResp
type ListProvidersResp struct {
	Code uint32             `json:"code"`
	Msg  string             `json:"msg"`
	Data []ProviderMetadata `json:"data"`
}

// swagger:model GetProviderSchemaResp
type GetProviderSchemaResp struct {
	Code uint32              `json:"code"`
	Msg  string              `json:"msg"`
	Data *ProviderSchemaInfo `json:"data"`
}

// swagger:model TestConnectionReq
type TestConnectionReq struct {
	ProviderId string                 `json:"providerId"`
	Config     map[string]interface{} `json:"config"`
}

type TestConnectionData struct {
	Success bool   `json:"success"`
	Message string `json:"message,omitempty"`
}

// swagger:model TestConnectionResp
type TestConnectionResp struct {
	Code uint32              `json:"code"`
	Msg  string              `json:"msg"`
	Data *TestConnectionData `json:"data"`
}

// swagger:model GetProviderSchemaReq
type GetProviderSchemaReq struct {
	ProviderId string `json:"provider_id"`
}

// swagger:model DataTargetInfo
type DataTargetInfo struct {
	Id               uint64  `json:"id"`
	CreatedAt        int64   `json:"createdAt"`
	UpdatedAt        int64   `json:"updatedAt"`
	Status           uint8   `json:"status"`
	TenantId         uint64  `json:"tenantId"`
	TargetName       string  `json:"targetName"`
	TargetType       string  `json:"targetType"`
	TargetSchema     *string `json:"targetSchema,optional"`
	ValidationRules  *string `json:"validationRules,optional"`
	UniqueKeys       *string `json:"uniqueKeys,optional"`
	ConnectionConfig *string `json:"connectionConfig,optional"`
	Description      *string `json:"description,optional"`
	Metadata         *string `json:"metadata,optional"`
}

// swagger:model CreateDataTargetReq
type CreateDataTargetReq struct {
	TargetName       string  `json:"targetName"`
	TargetType       *string `json:"targetType,optional"`
	TargetSchema     *string `json:"targetSchema,optional"`
	ValidationRules  *string `json:"validationRules,optional"`
	UniqueKeys       *string `json:"uniqueKeys,optional"`
	ConnectionConfig *string `json:"connectionConfig,optional"`
	Description      *string `json:"description,optional"`
	Metadata         *string `json:"metadata,optional"`
}

// swagger:model UpdateDataTargetReq
type UpdateDataTargetReq struct {
	Id               uint64  `json:"id"`
	TargetName       *string `json:"targetName,optional"`
	TargetType       *string `json:"targetType,optional"`
	TargetSchema     *string `json:"targetSchema,optional"`
	ValidationRules  *string `json:"validationRules,optional"`
	UniqueKeys       *string `json:"uniqueKeys,optional"`
	ConnectionConfig *string `json:"connectionConfig,optional"`
	Description      *string `json:"description,optional"`
	Metadata         *string `json:"metadata,optional"`
}

// swagger:model DataTargetListReq
type DataTargetListReq struct {
	Page       uint64  `json:"page"`
	PageSize   uint64  `json:"pageSize"`
	TargetType *string `json:"targetType,optional"`
	Keyword    *string `json:"keyword,optional"`
}

// swagger:model DataTargetListResp
type DataTargetListResp struct {
	Total uint64           `json:"total"`
	Data  []DataTargetInfo `json:"data"`
}

// swagger:model WorkerMetricsInfo
type WorkerMetricsInfo struct {
	Id                 uint64  `json:"id"`
	CreatedAt          int64   `json:"createdAt"`
	UpdatedAt          int64   `json:"updatedAt"`
	TenantId           uint64  `json:"tenantId"`
	WorkerId           string  `json:"workerId"`
	CpuUsagePercent    float64 `json:"cpuUsagePercent"`
	MemoryUsagePercent float64 `json:"memoryUsagePercent"`
	CurrentTaskCount   int64   `json:"currentTaskCount"`
	ThroughputRate     float64 `json:"throughputRate"`
	MetricTime         int64   `json:"metricTime"`
	Metadata           *string `json:"metadata,optional"`
}

// swagger:model CreateWorkerMetricsReq
type CreateWorkerMetricsReq struct {
	WorkerId           string  `json:"workerId"`
	CpuUsagePercent    float64 `json:"cpuUsagePercent"`
	MemoryUsagePercent float64 `json:"memoryUsagePercent"`
	CurrentTaskCount   int64   `json:"currentTaskCount"`
	ThroughputRate     float64 `json:"throughputRate"`
	Metadata           *string `json:"metadata,optional"`
}

// swagger:model WorkerMetricsListReq
type WorkerMetricsListReq struct {
	Page      uint64  `json:"page"`
	PageSize  uint64  `json:"pageSize"`
	WorkerId  *string `json:"workerId,optional"`
	StartTime *int64  `json:"startTime,optional"`
	EndTime   *int64  `json:"endTime,optional"`
}

// swagger:model WorkerMetricsListResp
type WorkerMetricsListResp struct {
	Total uint64              `json:"total"`
	Data  []WorkerMetricsInfo `json:"data"`
}

// 字段映射信息
// swagger:model FieldMappingInfo
type FieldMappingInfo struct {
	BaseIDInfo
	// 基础信息
	MappingName string `json:"mappingName"` // 映射名称
	Description string `json:"description"` // 映射描述
	MappingType string `json:"mappingType"` // 映射类型: input, output, transform, validation
	IsActive    bool   `json:"isActive"`    // 是否启用
	// 源字段信息
	SourceField     string `json:"sourceField"`     // 源字段名称
	SourceFieldPath string `json:"sourceFieldPath"` // 源字段路径(支持嵌套)
	SourceDataType  string `json:"sourceDataType"`  // 源数据类型
	SourceFormat    string `json:"sourceFormat"`    // 源字段格式
	// 目标字段信息
	TargetField     string `json:"targetField"`     // 目标字段名称
	TargetFieldPath string `json:"targetFieldPath"` // 目标字段路径(支持嵌套)
	TargetDataType  string `json:"targetDataType"`  // 目标数据类型
	TargetFormat    string `json:"targetFormat"`    // 目标字段格式
	// 转换配置
	TransformType   string `json:"transformType"`   // 转换类型: direct, format, calculate, lookup, conditional, custom
	TransformConfig string `json:"transformConfig"` // 转换配置JSON
	// 验证配置
	DefaultValue    string `json:"defaultValue"`    // 默认值
	AllowNull       bool   `json:"allowNull"`       // 允许空值
	IsRequired      bool   `json:"isRequired"`      // 是否必填
	ValidationRules string `json:"validationRules"` // 验证规则JSON数组
	ValidationRegex string `json:"validationRegex"` // 验证正则表达式
	// 查找表配置
	LookupTable         string `json:"lookupTable"`         // 查找表JSON
	LookupCaseSensitive bool   `json:"lookupCaseSensitive"` // 查找是否区分大小写
	// 条件规则
	ConditionRules string `json:"conditionRules"` // 条件规则JSON数组
	// 优先级和排序
	Priority  int `json:"priority"`  // 优先级
	SortOrder int `json:"sortOrder"` // 排序顺序
	// 关联信息
	DiscoveryPoolId *uint64 `json:"discoveryPoolId,optional"` // 关联发现池ID
	InputTaskId     *uint64 `json:"inputTaskId,optional"`     // 关联输入任务ID
	OutputTaskId    *uint64 `json:"outputTaskId,optional"`    // 关联输出任务ID
	// 使用统计
	UsageCount   int64   `json:"usageCount"`           // 使用次数
	SuccessCount int64   `json:"successCount"`         // 成功次数
	FailedCount  int64   `json:"failedCount"`          // 失败次数
	LastUsedAt   *int64  `json:"lastUsedAt,optional"`  // 最后使用时间
	LastError    *string `json:"lastError,optional"`   // 最后错误信息
	LastErrorAt  *int64  `json:"lastErrorAt,optional"` // 最后错误时间
	// 版本控制
	Version        string `json:"version"`        // 版本号
	VersionHistory string `json:"versionHistory"` // 版本历史JSON数组
	// 扩展元数据
	Metadata string `json:"metadata"` // 扩展元数据JSON
}

// 字段映射列表响应
// swagger:model FieldMappingListResp
type FieldMappingListResp struct {
	BaseDataInfo
	Data FieldMappingListData `json:"data"`
}

type FieldMappingListData struct {
	BaseListInfo
	Data []FieldMappingInfo `json:"data"`
}

// 字段映射信息响应
// swagger:model FieldMappingInfoResp
type FieldMappingInfoResp struct {
	BaseDataInfo
	Data FieldMappingInfo `json:"data"`
}

// 创建字段映射请求
// swagger:model CreateFieldMappingReq
type CreateFieldMappingReq struct {
	MappingName         string  `json:"mappingName"`                  // 映射名称
	Description         *string `json:"description,optional"`         // 映射描述
	MappingType         string  `json:"mappingType"`                  // 映射类型
	IsActive            *bool   `json:"isActive,optional"`            // 是否启用
	SourceField         string  `json:"sourceField"`                  // 源字段名称
	SourceFieldPath     *string `json:"sourceFieldPath,optional"`     // 源字段路径
	SourceDataType      *string `json:"sourceDataType,optional"`      // 源数据类型
	SourceFormat        *string `json:"sourceFormat,optional"`        // 源字段格式
	TargetField         string  `json:"targetField"`                  // 目标字段名称
	TargetFieldPath     *string `json:"targetFieldPath,optional"`     // 目标字段路径
	TargetDataType      *string `json:"targetDataType,optional"`      // 目标数据类型
	TargetFormat        *string `json:"targetFormat,optional"`        // 目标字段格式
	TransformType       *string `json:"transformType,optional"`       // 转换类型
	TransformConfig     *string `json:"transformConfig,optional"`     // 转换配置JSON
	DefaultValue        *string `json:"defaultValue,optional"`        // 默认值
	AllowNull           *bool   `json:"allowNull,optional"`           // 允许空值
	IsRequired          *bool   `json:"isRequired,optional"`          // 是否必填
	ValidationRules     *string `json:"validationRules,optional"`     // 验证规则
	ValidationRegex     *string `json:"validationRegex,optional"`     // 验证正则
	LookupTable         *string `json:"lookupTable,optional"`         // 查找表
	LookupCaseSensitive *bool   `json:"lookupCaseSensitive,optional"` // 查找区分大小写
	ConditionRules      *string `json:"conditionRules,optional"`      // 条件规则
	Priority            *int    `json:"priority,optional"`            // 优先级
	SortOrder           *int    `json:"sortOrder,optional"`           // 排序
	DiscoveryPoolId     *uint64 `json:"discoveryPoolId,optional"`     // 关联发现池ID
	InputTaskId         *uint64 `json:"inputTaskId,optional"`         // 关联输入任务ID
	OutputTaskId        *uint64 `json:"outputTaskId,optional"`        // 关联输出任务ID
	Version             *string `json:"version,optional"`             // 版本号
	Metadata            *string `json:"metadata,optional"`            // 扩展元数据
}

// 更新字段映射请求
// swagger:model UpdateFieldMappingReq
type UpdateFieldMappingReq struct {
	Id                  uint64  `json:"id"`                           // 字段映射ID
	MappingName         *string `json:"mappingName,optional"`         // 映射名称
	Description         *string `json:"description,optional"`         // 映射描述
	MappingType         *string `json:"mappingType,optional"`         // 映射类型
	IsActive            *bool   `json:"isActive,optional"`            // 是否启用
	SourceField         *string `json:"sourceField,optional"`         // 源字段名称
	SourceFieldPath     *string `json:"sourceFieldPath,optional"`     // 源字段路径
	SourceDataType      *string `json:"sourceDataType,optional"`      // 源数据类型
	SourceFormat        *string `json:"sourceFormat,optional"`        // 源字段格式
	TargetField         *string `json:"targetField,optional"`         // 目标字段名称
	TargetFieldPath     *string `json:"targetFieldPath,optional"`     // 目标字段路径
	TargetDataType      *string `json:"targetDataType,optional"`      // 目标数据类型
	TargetFormat        *string `json:"targetFormat,optional"`        // 目标字段格式
	TransformType       *string `json:"transformType,optional"`       // 转换类型
	TransformConfig     *string `json:"transformConfig,optional"`     // 转换配置JSON
	DefaultValue        *string `json:"defaultValue,optional"`        // 默认值
	AllowNull           *bool   `json:"allowNull,optional"`           // 允许空值
	IsRequired          *bool   `json:"isRequired,optional"`          // 是否必填
	ValidationRules     *string `json:"validationRules,optional"`     // 验证规则
	ValidationRegex     *string `json:"validationRegex,optional"`     // 验证正则
	LookupTable         *string `json:"lookupTable,optional"`         // 查找表
	LookupCaseSensitive *bool   `json:"lookupCaseSensitive,optional"` // 查找区分大小写
	ConditionRules      *string `json:"conditionRules,optional"`      // 条件规则
	Priority            *int    `json:"priority,optional"`            // 优先级
	SortOrder           *int    `json:"sortOrder,optional"`           // 排序
	DiscoveryPoolId     *uint64 `json:"discoveryPoolId,optional"`     // 关联发现池ID
	InputTaskId         *uint64 `json:"inputTaskId,optional"`         // 关联输入任务ID
	OutputTaskId        *uint64 `json:"outputTaskId,optional"`        // 关联输出任务ID
	Version             *string `json:"version,optional"`             // 版本号
	Metadata            *string `json:"metadata,optional"`            // 扩展元数据
}

// 字段映射列表查询请求
// swagger:model GetFieldMappingListReq
type GetFieldMappingListReq struct {
	PageInfo
	MappingName *string `form:"mappingName,optional" json:"mappingName,optional"` // 名称过滤
	MappingType *string `form:"mappingType,optional" json:"mappingType,optional"` // 类型过滤
	IsActive    *bool   `form:"isActive,optional" json:"isActive,optional"`       // 状态过滤
}

// 输入任务信息
// swagger:model InputTaskInfo
type InputTaskInfo struct {
	BaseIDInfo
	// 基础信息
	Name        string `json:"name"`        // 任务名称
	Description string `json:"description"` // 任务描述
	TaskType    string `json:"taskType"`    // 任务类型: file, api, sdk, builtin, manual
	TaskStatus  string `json:"taskStatus"`  // 任务状态: pending, running, completed, failed, cancelled, paused
	Priority    int    `json:"priority"`    // 优先级
	// 超时配置
	TimeoutSeconds int `json:"timeoutSeconds"` // 超时时间(秒)
	// 任务配置
	TaskConfig       string `json:"taskConfig"`       // 任务配置JSON
	ValidationConfig string `json:"validationConfig"` // 验证配置JSON
	OutputTargets    string `json:"outputTargets"`    // 输出目标JSON数组
	// 调度信息
	ScheduledAt *int64 `json:"scheduledAt,optional"` // 计划执行时间
	StartedAt   *int64 `json:"startedAt,optional"`   // 开始执行时间
	CompletedAt *int64 `json:"completedAt,optional"` // 完成时间
	// 处理统计
	TotalRecords     int64 `json:"totalRecords"`     // 总记录数
	ProcessedRecords int64 `json:"processedRecords"` // 已处理记录数
	SuccessRecords   int64 `json:"successRecords"`   // 成功记录数
	FailedRecords    int64 `json:"failedRecords"`    // 失败记录数
	// 错误信息
	ErrorMessage *string `json:"errorMessage,optional"` // 错误消息
	ErrorDetails string  `json:"errorDetails"`          // 错误详情JSON
	// 重试配置
	MaxRetry    int    `json:"maxRetry"`             // 最大重试次数
	RetryCount  int    `json:"retryCount"`           // 已重试次数
	NextRetryAt *int64 `json:"nextRetryAt,optional"` // 下次重试时间
	// 导入模式配置
	ImportMode       string `json:"importMode"`       // 导入模式: create_only, update_only, upsert, merge
	ConflictStrategy string `json:"conflictStrategy"` // 冲突策略: skip, overwrite, merge, error
	UniqueKeys       string `json:"uniqueKeys"`       // 唯一键字段列表JSON
	// 审核流程
	ApprovalStatus  string  `json:"approvalStatus"`           // 审核状态: pending, approved, rejected
	ApprovedBy      *uint64 `json:"approvedBy,optional"`      // 审核人ID
	ApprovedAt      *int64  `json:"approvedAt,optional"`      // 审核时间
	RejectionReason *string `json:"rejectionReason,optional"` // 拒绝原因
	// 关联信息
	DiscoveryPoolId *uint64 `json:"discoveryPoolId,optional"` // 关联发现池ID
	WorkerId        *string `json:"workerId,optional"`        // 执行工作节点ID
	// 进度信息
	ProgressPercent int    `json:"progressPercent"` // 进度百分比
	ProgressMessage string `json:"progressMessage"` // 进度消息
	// 扩展元数据
	Metadata string `json:"metadata"` // 扩展元数据JSON
}

// 输入任务列表响应
// swagger:model InputTaskListResp
type InputTaskListResp struct {
	BaseDataInfo
	Data InputTaskListData `json:"data"`
}

type InputTaskListData struct {
	BaseListInfo
	Data []InputTaskInfo `json:"data"`
}

// 输入任务信息响应
// swagger:model InputTaskInfoResp
type InputTaskInfoResp struct {
	BaseDataInfo
	Data InputTaskInfo `json:"data"`
}

// 创建输入任务请求
// swagger:model CreateInputTaskReq
type CreateInputTaskReq struct {
	Name             string  `json:"name"`                      // 任务名称
	Description      *string `json:"description,optional"`      // 任务描述
	TaskType         string  `json:"taskType"`                  // 任务类型
	Priority         *int    `json:"priority,optional"`         // 优先级
	TimeoutSeconds   *int    `json:"timeoutSeconds,optional"`   // 超时时间
	TaskConfig       *string `json:"taskConfig,optional"`       // 任务配置
	ValidationConfig *string `json:"validationConfig,optional"` // 验证配置
	OutputTargets    *string `json:"outputTargets,optional"`    // 输出目标
	ScheduledAt      *int64  `json:"scheduledAt,optional"`      // 计划执行时间
	MaxRetry         *int    `json:"maxRetry,optional"`         // 最大重试次数
	ImportMode       *string `json:"importMode,optional"`       // 导入模式
	ConflictStrategy *string `json:"conflictStrategy,optional"` // 冲突策略
	UniqueKeys       *string `json:"uniqueKeys,optional"`       // 唯一键列表JSON
	DiscoveryPoolId  *uint64 `json:"discoveryPoolId,optional"`  // 关联发现池ID
	Metadata         *string `json:"metadata,optional"`         // 扩展元数据
}

// 更新输入任务请求
// swagger:model UpdateInputTaskReq
type UpdateInputTaskReq struct {
	Id               uint64  `json:"id"`                        // 任务ID
	Name             *string `json:"name,optional"`             // 任务名称
	Description      *string `json:"description,optional"`      // 任务描述
	TaskType         *string `json:"taskType,optional"`         // 任务类型
	Priority         *int    `json:"priority,optional"`         // 优先级
	TimeoutSeconds   *int    `json:"timeoutSeconds,optional"`   // 超时时间
	TaskConfig       *string `json:"taskConfig,optional"`       // 任务配置
	ValidationConfig *string `json:"validationConfig,optional"` // 验证配置
	OutputTargets    *string `json:"outputTargets,optional"`    // 输出目标
	ScheduledAt      *int64  `json:"scheduledAt,optional"`      // 计划执行时间
	MaxRetry         *int    `json:"maxRetry,optional"`         // 最大重试次数
	DiscoveryPoolId  *uint64 `json:"discoveryPoolId,optional"`  // 关联发现池ID
	Metadata         *string `json:"metadata,optional"`         // 扩展元数据
}

// 输入任务列表查询请求
// swagger:model GetInputTaskListReq
type GetInputTaskListReq struct {
	PageInfo
	Name            *string `json:"name,optional"`            // 名称过滤
	TaskType        *string `json:"taskType,optional"`        // 类型过滤
	TaskStatus      *string `json:"taskStatus,optional"`      // 状态过滤
	ApprovalStatus  *string `json:"approvalStatus,optional"`  // 审核状态过滤
	DiscoveryPoolId *uint64 `json:"discoveryPoolId,optional"` // 发现池过滤
}

// 审核输入任务请求
// swagger:model ApproveInputTaskReq
type ApproveInputTaskReq struct {
	Id     uint64  `json:"id"`              // 任务ID
	Action string  `json:"action"`          // 审核动作: approve, reject
	Reason *string `json:"reason,optional"` // 拒绝原因(拒绝时必填)
}

// 输出任务信息
// swagger:model OutputTaskInfo
type OutputTaskInfo struct {
	BaseIDInfo
	// 基础信息
	Name        string `json:"name"`        // 任务名称
	Description string `json:"description"` // 任务描述
	OutputType  string `json:"outputType"`  // 输出类型: kafka, elasticsearch, database, api, file, webhook, email
	TaskStatus  string `json:"taskStatus"`  // 任务状态: pending, running, completed, failed, cancelled, paused
	Priority    int    `json:"priority"`    // 优先级
	// 超时配置
	TimeoutSeconds int `json:"timeoutSeconds"` // 超时时间(秒)
	// 数据源配置
	DataSource   string `json:"dataSource"`   // 数据源JSON
	OutputFormat string `json:"outputFormat"` // 输出格式: json, xml, csv, excel, txt, parquet, avro
	// 推送目标
	PushTargets       string `json:"pushTargets"`       // 推送目标JSON数组
	CompressionConfig string `json:"compressionConfig"` // 压缩配置JSON
	TransformConfig   string `json:"transformConfig"`   // 转换配置JSON
	// 调度信息
	ScheduledAt *int64 `json:"scheduledAt,optional"` // 计划执行时间
	StartedAt   *int64 `json:"startedAt,optional"`   // 开始执行时间
	CompletedAt *int64 `json:"completedAt,optional"` // 完成时间
	// 处理统计
	TotalRecords     int64  `json:"totalRecords"`     // 总记录数
	ProcessedRecords int64  `json:"processedRecords"` // 已处理记录数
	SuccessRecords   int64  `json:"successRecords"`   // 成功记录数
	FailedRecords    int64  `json:"failedRecords"`    // 失败记录数
	OutputFilePath   string `json:"outputFilePath"`   // 输出文件路径
	OutputFileSize   int64  `json:"outputFileSize"`   // 输出文件大小
	// 错误信息
	ErrorMessage *string `json:"errorMessage,optional"` // 错误消息
	ErrorDetails string  `json:"errorDetails"`          // 错误详情JSON
	// 重试配置
	MaxRetry    int    `json:"maxRetry"`             // 最大重试次数
	RetryCount  int    `json:"retryCount"`           // 已重试次数
	NextRetryAt *int64 `json:"nextRetryAt,optional"` // 下次重试时间
	// 执行信息
	WorkerId        *string `json:"workerId,optional"` // 执行工作节点ID
	ProgressPercent int     `json:"progressPercent"`   // 进度百分比
	ProgressMessage string  `json:"progressMessage"`   // 进度消息
	ThroughputRate  float64 `json:"throughputRate"`    // 吞吐率(记录/秒)
	DurationSeconds int     `json:"durationSeconds"`   // 执行时长(秒)
	// 触发信息
	TriggerSource string  `json:"triggerSource"`          // 触发源
	TriggerTaskId *uint64 `json:"triggerTaskId,optional"` // 触发任务ID
	Dependencies  string  `json:"dependencies"`           // 依赖任务JSON数组
	// 扩展元数据
	Metadata string `json:"metadata"` // 扩展元数据JSON
}

// 输出任务列表响应
// swagger:model OutputTaskListResp
type OutputTaskListResp struct {
	BaseDataInfo
	Data OutputTaskListData `json:"data"`
}

type OutputTaskListData struct {
	BaseListInfo
	Data []OutputTaskInfo `json:"data"`
}

// 输出任务信息响应
// swagger:model OutputTaskInfoResp
type OutputTaskInfoResp struct {
	BaseDataInfo
	Data OutputTaskInfo `json:"data"`
}

// 创建输出任务请求
// swagger:model CreateOutputTaskReq
type CreateOutputTaskReq struct {
	Name              string  `json:"name"`                       // 任务名称
	Description       *string `json:"description,optional"`       // 任务描述
	OutputType        string  `json:"outputType"`                 // 输出类型
	Priority          *int    `json:"priority,optional"`          // 优先级
	TimeoutSeconds    *int    `json:"timeoutSeconds,optional"`    // 超时时间
	DataSource        *string `json:"dataSource,optional"`        // 数据源
	OutputFormat      *string `json:"outputFormat,optional"`      // 输出格式
	PushTargets       *string `json:"pushTargets,optional"`       // 推送目标
	CompressionConfig *string `json:"compressionConfig,optional"` // 压缩配置
	TransformConfig   *string `json:"transformConfig,optional"`   // 转换配置
	ScheduledAt       *int64  `json:"scheduledAt,optional"`       // 计划执行时间
	MaxRetry          *int    `json:"maxRetry,optional"`          // 最大重试次数
	TriggerSource     *string `json:"triggerSource,optional"`     // 触发源
	TriggerTaskId     *uint64 `json:"triggerTaskId,optional"`     // 触发任务ID
	Dependencies      *string `json:"dependencies,optional"`      // 依赖任务
	Metadata          *string `json:"metadata,optional"`          // 扩展元数据
}

// 更新输出任务请求
// swagger:model UpdateOutputTaskReq
type UpdateOutputTaskReq struct {
	Id                uint64  `json:"id"`                         // 任务ID
	Name              *string `json:"name,optional"`              // 任务名称
	Description       *string `json:"description,optional"`       // 任务描述
	OutputType        *string `json:"outputType,optional"`        // 输出类型
	Priority          *int    `json:"priority,optional"`          // 优先级
	TimeoutSeconds    *int    `json:"timeoutSeconds,optional"`    // 超时时间
	DataSource        *string `json:"dataSource,optional"`        // 数据源
	OutputFormat      *string `json:"outputFormat,optional"`      // 输出格式
	PushTargets       *string `json:"pushTargets,optional"`       // 推送目标
	CompressionConfig *string `json:"compressionConfig,optional"` // 压缩配置
	TransformConfig   *string `json:"transformConfig,optional"`   // 转换配置
	ScheduledAt       *int64  `json:"scheduledAt,optional"`       // 计划执行时间
	MaxRetry          *int    `json:"maxRetry,optional"`          // 最大重试次数
	TriggerSource     *string `json:"triggerSource,optional"`     // 触发源
	TriggerTaskId     *uint64 `json:"triggerTaskId,optional"`     // 触发任务ID
	Dependencies      *string `json:"dependencies,optional"`      // 依赖任务
	Metadata          *string `json:"metadata,optional"`          // 扩展元数据
}

// 输出任务列表查询请求
// swagger:model GetOutputTaskListReq
type GetOutputTaskListReq struct {
	PageInfo
	Name       *string `form:"name,optional" json:"name,optional"`             // 名称过滤
	OutputType *string `form:"outputType,optional" json:"outputType,optional"` // 类型过滤
	TaskStatus *string `form:"taskStatus,optional" json:"taskStatus,optional"` // 状态过滤
}

// 任务日志信息
// swagger:model TaskLogInfo
type TaskLogInfo struct {
	BaseIDInfo
	// 关联信息
	TaskId   uint64 `json:"taskId"`   // 任务ID
	TaskType string `json:"taskType"` // 任务类型: input, output
	// 日志信息
	Level   string `json:"level"`   // 日志级别: debug, info, warn, error
	Message string `json:"message"` // 日志消息
	Details string `json:"details"` // 详细信息JSON
}

// 任务日志列表响应
// swagger:model TaskLogListResp
type TaskLogListResp struct {
	BaseDataInfo
	Data TaskLogListData `json:"data"`
}

type TaskLogListData struct {
	BaseListInfo
	Data []TaskLogInfo `json:"data"`
}

// 任务日志信息响应
// swagger:model TaskLogInfoResp
type TaskLogInfoResp struct {
	BaseDataInfo
	Data TaskLogInfo `json:"data"`
}

// 创建任务日志请求
// swagger:model CreateTaskLogReq
type CreateTaskLogReq struct {
	TaskId   uint64  `json:"taskId"`           // 任务ID
	TaskType string  `json:"taskType"`         // 任务类型
	Level    string  `json:"level"`            // 日志级别
	Message  string  `json:"message"`          // 日志消息
	Details  *string `json:"details,optional"` // 详细信息
}

// 任务日志列表查询请求
// swagger:model GetTaskLogListReq
type GetTaskLogListReq struct {
	PageInfo
	TaskId   *uint64 `form:"taskId,optional" json:"taskId,optional"`     // 任务ID过滤
	TaskType *string `form:"taskType,optional" json:"taskType,optional"` // 任务类型过滤
	Level    *string `form:"level,optional" json:"level,optional"`       // 日志级别过滤
}

// 映射日志信息
// swagger:model MappingLogInfo
type MappingLogInfo struct {
	BaseIDInfo
	// 关联信息
	FieldMappingId uint64 `json:"fieldMappingId"` // 字段映射ID
	// 日志信息
	Level   string `json:"level"`   // 日志级别: debug, info, warn, error
	Message string `json:"message"` // 日志消息
	Details string `json:"details"` // 详细信息JSON
}

// 映射日志列表响应
// swagger:model MappingLogListResp
type MappingLogListResp struct {
	BaseDataInfo
	Data MappingLogListData `json:"data"`
}

type MappingLogListData struct {
	BaseListInfo
	Data []MappingLogInfo `json:"data"`
}

// 映射日志信息响应
// swagger:model MappingLogInfoResp
type MappingLogInfoResp struct {
	BaseDataInfo
	Data MappingLogInfo `json:"data"`
}

// 创建映射日志请求
// swagger:model CreateMappingLogReq
type CreateMappingLogReq struct {
	FieldMappingId uint64  `json:"fieldMappingId"`   // 字段映射ID
	Level          string  `json:"level"`            // 日志级别
	Message        string  `json:"message"`          // 日志消息
	Details        *string `json:"details,optional"` // 详细信息
}

// 映射日志列表查询请求
// swagger:model GetMappingLogListReq
type GetMappingLogListReq struct {
	PageInfo
	FieldMappingId *uint64 `form:"fieldMappingId,optional" json:"fieldMappingId,optional"` // 字段映射ID过滤
	Level          *string `form:"level,optional" json:"level,optional"`                   // 日志级别过滤
}
