// Code generated by goctl. DO NOT EDIT.
// goctls v1.12.1

package handler

import (
	"net/http"

	base "github.com/coder-lulu/newbee-io-api/internal/handler/base"
	data_target "github.com/coder-lulu/newbee-io-api/internal/handler/data_target"
	discovery_pool "github.com/coder-lulu/newbee-io-api/internal/handler/discovery_pool"
	discovery_template "github.com/coder-lulu/newbee-io-api/internal/handler/discovery_template"
	discoveryprovider "github.com/coder-lulu/newbee-io-api/internal/handler/discoveryprovider"
	field_mapping "github.com/coder-lulu/newbee-io-api/internal/handler/field_mapping"
	input_task "github.com/coder-lulu/newbee-io-api/internal/handler/input_task"
	mapping_log "github.com/coder-lulu/newbee-io-api/internal/handler/mapping_log"
	output_task "github.com/coder-lulu/newbee-io-api/internal/handler/output_task"
	task_log "github.com/coder-lulu/newbee-io-api/internal/handler/task_log"
	worker_metrics "github.com/coder-lulu/newbee-io-api/internal/handler/worker_metrics"
	"github.com/coder-lulu/newbee-io-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/init/database",
				Handler: base.InitDatabaseHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/discovery_pool/create",
				Handler: discovery_pool.CreateDiscoveryPoolHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/discovery_pool/update",
				Handler: discovery_pool.UpdateDiscoveryPoolHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/discovery_pool/delete",
				Handler: discovery_pool.DeleteDiscoveryPoolHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/discovery_pool/:id",
				Handler: discovery_pool.GetDiscoveryPoolHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/discovery_pool/list",
				Handler: discovery_pool.GetDiscoveryPoolListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/discovery_pool/enable",
				Handler: discovery_pool.EnableDiscoveryPoolHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/discovery_pool/disable",
				Handler: discovery_pool.DisableDiscoveryPoolHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/discovery_pool/trigger",
				Handler: discovery_pool.TriggerDiscoveryPoolHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/discovery_pool/stats/:id",
				Handler: discovery_pool.GetDiscoveryPoolStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/discovery_pool/approve",
				Handler: discovery_pool.ApproveDiscoveryPoolHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/discovery_template/create",
				Handler: discovery_template.CreateDiscoveryTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/discovery_template/update",
				Handler: discovery_template.UpdateDiscoveryTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/discovery_template/delete",
				Handler: discovery_template.DeleteDiscoveryTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/discovery_template/info",
				Handler: discovery_template.GetDiscoveryTemplateByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/discovery_template/list",
				Handler: discovery_template.GetDiscoveryTemplateListHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取所有发现Provider列表
				Method:  http.MethodPost,
				Path:    "/discoveryprovider/list_discovery_providers",
				Handler: discoveryprovider.ListDiscoveryProvidersHandler(serverCtx),
			},
			{
				// 获取指定Provider的Schema
				Method:  http.MethodPost,
				Path:    "/discoveryprovider/get_provider_schema",
				Handler: discoveryprovider.GetProviderSchemaHandler(serverCtx),
			},
			{
				// 测试Provider连接
				Method:  http.MethodPost,
				Path:    "/discoveryprovider/test_provider_connection",
				Handler: discoveryprovider.TestProviderConnectionHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/data_target/create",
				Handler: data_target.CreateDataTargetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/data_target/update",
				Handler: data_target.UpdateDataTargetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/data_target/delete",
				Handler: data_target.DeleteDataTargetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/data_target/info",
				Handler: data_target.GetDataTargetByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/data_target/list",
				Handler: data_target.GetDataTargetListHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/worker_metrics/create",
				Handler: worker_metrics.CreateWorkerMetricsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/worker_metrics/list",
				Handler: worker_metrics.GetWorkerMetricsListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/worker_metrics/info",
				Handler: worker_metrics.GetWorkerMetricsByIdHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/field_mapping/create",
				Handler: field_mapping.CreateFieldMappingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/field_mapping/update",
				Handler: field_mapping.UpdateFieldMappingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/field_mapping/delete",
				Handler: field_mapping.DeleteFieldMappingHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/field_mapping/:id",
				Handler: field_mapping.GetFieldMappingHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/field_mapping/list",
				Handler: field_mapping.GetFieldMappingListHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/input_task/create",
				Handler: input_task.CreateInputTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/input_task/update",
				Handler: input_task.UpdateInputTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/input_task/delete",
				Handler: input_task.DeleteInputTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/input_task/:id",
				Handler: input_task.GetInputTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/input_task/list",
				Handler: input_task.GetInputTaskListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/input_task/start",
				Handler: input_task.StartInputTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/input_task/pause",
				Handler: input_task.PauseInputTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/input_task/cancel",
				Handler: input_task.CancelInputTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/input_task/approve",
				Handler: input_task.ApproveInputTaskHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/output_task/create",
				Handler: output_task.CreateOutputTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/output_task/update",
				Handler: output_task.UpdateOutputTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/output_task/delete",
				Handler: output_task.DeleteOutputTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/output_task/:id",
				Handler: output_task.GetOutputTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/output_task/list",
				Handler: output_task.GetOutputTaskListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/output_task/start",
				Handler: output_task.StartOutputTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/output_task/pause",
				Handler: output_task.PauseOutputTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/output_task/cancel",
				Handler: output_task.CancelOutputTaskHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/task_log/create",
				Handler: task_log.CreateTaskLogHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/task_log/delete",
				Handler: task_log.DeleteTaskLogHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/task_log/:id",
				Handler: task_log.GetTaskLogHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/task_log/list",
				Handler: task_log.GetTaskLogListHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/mapping_log/create",
				Handler: mapping_log.CreateMappingLogHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/mapping_log/delete",
				Handler: mapping_log.DeleteMappingLogHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/mapping_log/:id",
				Handler: mapping_log.GetMappingLogHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/mapping_log/list",
				Handler: mapping_log.GetMappingLogListHandler(serverCtx),
			},
		},
	)
}
